In [48]:
import pandas as pd
import numpy as np

# Write a Python program to create and display a one-dimensional array-like object containing an array of data using Pandas module

In [5]:
data = pd.Series([1,2,3,4,5])
print(data)

0    1
1    2
2    3
3    4
4    5
dtype: int64


# Write a Python program to convert a Panda module Series to Python list and it's type

In [6]:
data = pd.Series([23,4,5,6])
print("Series:\n",data)
lis1 = list(data)
print("List",lis1)
print("Type:",type(lis1))

Series:
 0    23
1     4
2     5
3     6
dtype: int64
List [23, 4, 5, 6]
Type: <class 'list'>


# Write a Python program to add, subtract, multiple and divide two Pandas Series.

In [11]:
data1 = pd.Series([1,2,3,4])
data2=pd.Series([5,6,7,8])

In [14]:
print("Addition:\n",data1+data2)
print("Subtraction:\n",data1-data2)
print("Multiplication:\n",data1*data2)
print("Divide:\n",data1/data2)

Addition:
 0     6
1     8
2    10
3    12
dtype: int64
Subtraction:
 0   -4
1   -4
2   -4
3   -4
dtype: int64
Multiplication:
 0     5
1    12
2    21
3    32
dtype: int64
Divide:
 0    0.200000
1    0.333333
2    0.428571
3    0.500000
dtype: float64


# Write a Python program to get the largest integer smaller or equal to the division of the inputs.

In [15]:
data1 = pd.Series([1,2,3,4])
data2=pd.Series([5,6,7,8])

In [16]:
print("Equal:\n",data1==data2)
print("Larger:\n",data1>data2)
print("Smaller:\n",data1<data2)

Equal:
 0    False
1    False
2    False
3    False
dtype: bool
Larger:
 0    False
1    False
2    False
3    False
dtype: bool
Smaller:
 0    True
1    True
2    True
3    True
dtype: bool


# Write a Python program to convert a dictionary to a Pandas series. 

In [26]:
dictionary = {'Messi': 10, 'Suarez': 9, 'Neymar': 11, 'Arthur': 8}

In [27]:
data= pd.Series(dictionary)

In [28]:
data

Messi     10
Suarez     9
Neymar    11
Arthur     8
dtype: int64

In [29]:
 print(type(data))

<class 'pandas.core.series.Series'>


# Write a Python program to convert a NumPy array to a Pandas series 

In [31]:
array = np.array([1,2,3,4,5])
d = pd.Series(array)

In [32]:
d

0    1
1    2
2    3
3    4
4    5
dtype: int32

#  Write a Python program to change the data type of given a column or a Series 

In [40]:
data = pd.Series(['4','5','6','7','8','Suarez','Messi'])

In [38]:
data

0         4
1         5
2         6
3         7
4         8
5    Suarez
6     Messi
dtype: object

In [41]:
s = pd.to_numeric(data,errors='coerce')

In [42]:
print(s)

0    4.0
1    5.0
2    6.0
3    7.0
4    8.0
5    NaN
6    NaN
dtype: float64


# Write a Python Pandas program to convert the first column of a DataFrame as a Series.

In [50]:
df = {'Barca':["Messi","Neymar"],'Real Madrid':["Bale","Hazard"]}

In [51]:
df = pd.DataFrame(data = df)

In [52]:
df

Barca Real Madrid
0   Messi        Bale
1  Neymar      Hazard

In [53]:
s = pd.Series(df['Barca'])

In [54]:
s

0     Messi
1    Neymar
Name: Barca, dtype: object

# Write a Pandas program to convert a given Series to an array.

In [55]:
s = pd.Series(['100' '200' 'python' '300.12' '400'])

In [56]:
array = np.array(s)

In [57]:
print(array)

<PandasArray>
['100200python300.12400']
Length: 1, dtype: object


# Write a Pandas program to convert Series of lists to one Series

In [62]:
s = pd.Series([['Red', 'Green', 'White'],['Red', 'Black'],['Yellow']])

In [63]:
print(s)

0    [Red, Green, White]
1           [Red, Black]
2               [Yellow]
dtype: object

In [60]:
s = s.apply(pd.Series).stack().reset_index(drop=True)

In [61]:
print(s)

0       Red
1     Green
2     White
3       Red
4     Black
5    Yellow
dtype: object

#  Write a Pandas program to sort a given Series

In [81]:
s = pd.Series(["10","Messi","20","Roberto"]).sort_values()

In [82]:
print(s)

0         10
2         20
1      Messi
3    Roberto
dtype: object


# Write a Pandas program to add some data to an existing Series

In [84]:
s = pd.Series([10,20,30,40,50])

In [87]:
s = s.append(pd.Series([60,70,80,90,100]))

In [88]:
print(s)

0     10
1     20
2     30
3     40
4     50
0     60
1     70
2     80
3     90
4    100
dtype: int64


#  Write a Pandas program to create a subset of a given series based on value and condition.

In [89]:
s = pd.Series([10,20,30,40,50,60,70,80,90.100])

In [99]:
new_s = s[s<50]

In [100]:
print(new_s)

0    10.0
1    20.0
2    30.0
3    40.0
dtype: float64


#  Write a Pandas program to change the order of index of a given series.

In [105]:
s = pd.Series(["Messi","Suarez","Neymar","Xavi","Iniesta","Busquets"],index=['A','B','C','D','E','F'])

In [106]:
print(s)

A       Messi
B      Suarez
C      Neymar
D        Xavi
E     Iniesta
F    Busquets
dtype: object


In [108]:
print("After changing index")
s = s.reindex(index=['F','E','D','C','B','A'])
print(s)

After changing index
F    Busquets
E     Iniesta
D        Xavi
C      Neymar
B      Suarez
A       Messi
dtype: object


# Write a Pandas program to create the mean and standard deviation of the data of a given Series

In [109]:
s = pd.Series([10,20,30,40,50,60,70,80,90.100])

In [111]:
print("Mean:",s.mean())
print("Std Deviation:",s.std())

Mean: 50.01111111111111
Std Deviation: 27.404399484592087


# Write a Pandas program to get the items of a given series not present in another given series.

In [116]:
s1= pd.Series([10,20,30,40,50,60,70,80,90,100])
s2 = pd.Series([10,20,30,40,50])

In [117]:
s3 = s1[~ s1.isin(s2)]

In [118]:
s3

5     60
6     70
7     80
8     90
9    100
dtype: int64

# Write a Pandas program to compute the minimum, 25th percentile, median, 75th, and maximum of a given series.

In [127]:
import numpy as np
num_state = np.random.RandomState(100)
num_series = pd.Series(num_state.normal(10, 4, 20))
print("Original Series:")
print(num_series)
result = np.percentile(num_series, q=[0, 25, 50, 75, 100])
print("\nMinimum, 25th percentile, median, 75th, and maximum of a given series:")
print(result)

Original Series:
0      3.000938
1     11.370722
2     14.612143
3      8.990256
4     13.925283
5     12.056875
6     10.884719
7      5.719827
8      9.242017
9     11.020006
10     8.167892
11    11.740654
12     7.665620
13    13.267388
14    12.690883
15     9.582355
16     7.874878
17    14.118931
18     8.247458
19     5.526727
dtype: float64

Minimum, 25th percentile, median, 75th, and maximum of a given series:
[ 3.00093811  8.09463867 10.23353705 12.21537733 14.61214321]


# Write a Pandas program to calculate the frequency counts of each unique value of a given series. 

In [128]:
s1= pd.Series([10,20,30,40,50,60,70,80,90,100])

In [134]:
s1.value_counts()

30     1
60     1
10     1
40     1
70     1
90     1
20     1
50     1
100    1
80     1
dtype: int64

# Write a Pandas program to display most frequent value in a given series and replace everything else as 'Other' in the series

In [138]:
s1= pd.Series([10,20,30,40,50,60,70,80,100,100])

In [141]:
print("Top 2 Freq:", s1.value_counts())
result = s1[~s1.isin(s1.value_counts().index[:1])] = 'Other'

Top 2 Freq: Other    8
100      2
dtype: int64


#  Write a Pandas program to find the positions of numbers that are multiples of 5 of a given series. 

In [147]:
s1= pd.Series([1,2,3,4,5,6,7,8,9,10])

In [148]:
result = np.argwhere(s1%5==0)

C:\ProgramData\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py:56: FutureWarning: Series.nonzero() is deprecated and will be removed in a future version.Use Series.to_numpy().nonzero() instead
  return getattr(obj, method)(*args, **kwds)


In [149]:
result

array([[4],
       [9]], dtype=int64)

# Write a Pandas program to extract items at given positions of a given series.

In [155]:
num_series = pd.Series(list('2390238923902390239023'))
element_pos = [1, 2, 6, 11, 4]
#print("Original Series:")
#print(num_series)
result = num_series.take(element_pos)
print("\nExtract items at given positions of the said series:")
print(result)


Extract items at given positions of the said series:
1     3
2     9
6     8
11    0
4     2
dtype: object


# Write a Pandas program to get the positions of items of a given series in another given series

In [156]:
series1 = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
series2 = pd.Series([1, 3, 5, 7, 10])

In [157]:
result = [pd.Index(series1).get_loc(i) for i in series2]

In [158]:
result

[0, 2, 4, 6, 9]

# Write a Pandas program convert the first and last character of each word to upper case in each word of a given series.

In [159]:
series1 = pd.Series(['messi', 'suarez', 'neymar', 'rakitic'])

In [164]:
result = series1.map(lambda x:x[0].upper() + x[1:-1]+x[-1].upper())

In [165]:
result

0      MessI
1     SuareZ
2     NeymaR
3    RakitiC
dtype: object

# Write a Pandas program to calculate the number of characters in each word in a given series.

In [166]:
series1 = pd.Series(['messi', 'suarez', 'neymar', 'rakitic'])

In [168]:
for i in series1:
    print(len(i))

5
6
6
7


# Write a Pandas program to compute difference of differences between consecutive numbers of a given series.

In [171]:
series1 = pd.Series([1, 2, 3, 4, 8, 9, 7, 8, 9, 10])

In [172]:
print(series1.diff().tolist())

[nan, 1.0, 1.0, 1.0, 4.0, 1.0, -2.0, 1.0, 1.0, 1.0]


# Write a Pandas program to convert a series of date strings to a timeseries.

In [190]:
series = pd.Series(['13 Apr 2015', '13-04-2016', '20180413', '2014/04/13', '2016-04-13', '2019-04-13T11:20'])

In [191]:
date = pd.to_datetime(series)

In [192]:
date

0   2015-04-13 00:00:00
1   2016-04-13 00:00:00
2   2018-04-13 00:00:00
3   2014-04-13 00:00:00
4   2016-04-13 00:00:00
5   2019-04-13 11:20:00
dtype: datetime64[ns]

# Write a Pandas program to get the day of month, day of year, week number and day of week from a given series of date strings.

In [193]:
from dateutil.parser import parse
date_series = pd.Series(['01 Jan 2015', '10-02-2016', '20180307', '2014/05/06', '2016-04-12', '2019-04-06T11:20'])
print("Original Series:")
print(date_series)
date_series = date_series.map(lambda x: parse(x))
print("Day of month:")
print(date_series.dt.day.tolist())
print("Day of year:")
print(date_series.dt.dayofyear.tolist())
print("Week number:")
print(date_series.dt.weekofyear.tolist())
print("Day of week:")
print(date_series.dt.weekday_name.tolist())

Original Series:
0         01 Jan 2015
1          10-02-2016
2            20180307
3          2014/05/06
4          2016-04-12
5    2019-04-06T11:20
dtype: object
Day of month:
[1, 2, 7, 6, 12, 6]
Day of year:
[1, 276, 66, 126, 103, 96]
Week number:
[1, 39, 10, 19, 15, 14]
Day of week:
['Thursday', 'Sunday', 'Wednesday', 'Tuesday', 'Tuesday', 'Saturday']


# Write a Pandas program to convert year-month string to dates adding a specified day of the month

In [194]:
date_series = pd.Series(['Jan 2015', 'Feb 2016', 'Mar 2017', 'Apr 2018', 'May 2019'])

In [199]:
result = date_series.map(lambda d: parse('13 ' + d))
print(result)

0   2015-01-13
1   2016-02-13
2   2017-03-13
3   2018-04-13
4   2019-05-13
dtype: datetime64[ns]


# Write a Pandas program to filter words from a given series that contain atleast two vowels.

In [12]:
from collections import Counter
s = pd.Series(["Messi","Suarez","Griezmaan","Ter"])

In [19]:
s.value_counts()

Griezmaan    1
Messi        1
Suarez       1
Ter          1
dtype: int64

In [24]:
result = s.map(lambda x:sum([Counter(x.lower()).get(i,0) for i in list('aeiou')])>=2)  

In [25]:
s[result]

0        Messi
1       Suarez
2    Griezmaan
dtype: object

# Write a Pandas program to compute the Euclidean distance between two given series.

In [29]:
from scipy.spatial import distance

In [27]:
s = pd.Series([10,20,30,40,50])
s1 = pd.Series([40,50,60,70,80])

In [30]:
result = distance.euclidean(s,s1)

In [31]:
result

67.08203932499369

# Write a Pandas program to find the positions of the values neighboured by smaller values on both sides in a given series

In [34]:
import numpy as np
nums = pd.Series([1, 8, 7, 5, 6, 5, 3, 4, 7, 1])

In [35]:
temp = np.diff(np.sign(np.diff(nums)))

In [36]:
result = np.where(temp == -2)[0] + 1

In [37]:
result

array([1, 4, 8], dtype=int64)

#  Write a Pandas program to replace missing white spaces in a given string with the least frequent character

In [38]:
str = "Krishna Gandhi"

In [40]:
s= pd.Series(list(str))

In [41]:
ele_fre = s.value_counts()

In [42]:
ele_fre

i    2
n    2
h    2
a    2
s    1
     1
r    1
d    1
G    1
K    1
dtype: int64

In [45]:
current_freq = ele_fre.dropna().index[-1]
result = "".join(s.replace(' ', current_freq))
print(result)

KrishnaKGandhi


# Write a Pandas program to compute the autocorrelations of a given numeric series.

### Autocorrelation, also known as serial correlation, is the correlation of a signal with a delayed copy of itself as a function of delay. Informally, it is the similarity between observations as a function of the time lag between them.

In [46]:
num_series = pd.Series(np.arange(15) + np.random.normal(1, 10, 15))
print("Original series:")
print(num_series)
autocorrelations = [num_series.autocorr(i).round(2) for i in range(11)]
print("\nAutocorrelations of the said series:")
print(autocorrelations[1:])

Original series:
0      9.866774
1      3.963429
2      4.321994
3      5.332970
4     -3.353997
5    -18.705606
6      3.872158
7     22.289070
8      0.709710
9     23.560802
10     3.000856
11    -2.758271
12     5.588446
13    13.059821
14     5.931364
dtype: float64

Autocorrelations of the said series:
[0.02, -0.2, -0.04, -0.29, -0.18, 0.47, 0.23, -0.36, 0.21, -0.07]


# Write a Pandas program to create a TimeSeries to display all the Sundays of given year.

In [47]:
result = pd.Series(pd.date_range('2020-01-01', periods=52, freq='W-SUN'))
print("All Sundays of 2020:")
print(result)

All Sundays of 2020:
0    2020-01-05
1    2020-01-12
2    2020-01-19
3    2020-01-26
4    2020-02-02
5    2020-02-09
6    2020-02-16
7    2020-02-23
8    2020-03-01
9    2020-03-08
10   2020-03-15
11   2020-03-22
12   2020-03-29
13   2020-04-05
14   2020-04-12
15   2020-04-19
16   2020-04-26
17   2020-05-03
18   2020-05-10
19   2020-05-17
20   2020-05-24
21   2020-05-31
22   2020-06-07
23   2020-06-14
24   2020-06-21
25   2020-06-28
26   2020-07-05
27   2020-07-12
28   2020-07-19
29   2020-07-26
30   2020-08-02
31   2020-08-09
32   2020-08-16
33   2020-08-23
34   2020-08-30
35   2020-09-06
36   2020-09-13
37   2020-09-20
38   2020-09-27
39   2020-10-04
40   2020-10-11
41   2020-10-18
42   2020-10-25
43   2020-11-01
44   2020-11-08
45   2020-11-15
46   2020-11-22
47   2020-11-29
48   2020-12-06
49   2020-12-13
50   2020-12-20
51   2020-12-27
dtype: datetime64[ns]
